nameOverride: ""
fullnameOverride: ""

imagePullPolicy: IfNotPresent
imagePullSecrets: {}
debug: false

image:
  registry: ghcr.io
  repository: boxboat/k8s-tpm-device
  tag: master

device:
  namespace: tpm.boxboat.io
  capacity: 1

priorityClassName: ""

podAnnotations: {}

# override the default podSecurityContext (defaults are commented out below)
securityContext: {}
#  readOnlyRootFilesystem: true
#  allowPrivilegeEscalation: false

# specify pod container resources
resources: {}

# add tolerations to the daemonset
tolerations: {}

extraVolumes: []
extraVolumeMounts: []
extraContainers: []
initContainers: []